import { supabase } from '@/integrations/supabase/client';

export interface LessonExportData {
  lessonTitle: string;
  topic: string;
  yearGroup: string;
  duration: number;
  completedAt: string;
  transcript: string;
  questionsAnswered: number;
  accuracy: number;
  keyPoints: string[];
}

export const lessonExportService = {
  async generateLessonPDF(conversationId: string): Promise<string> {
    try {
      const { data, error } = await supabase.functions.invoke('generate-lesson-pdf', {
        body: { conversationId }
      });

      if (error) throw error;
      if (!data?.pdfUrl) throw new Error('No PDF URL returned');

      return data.pdfUrl;
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw new Error('Failed to generate lesson summary PDF');
    }
  },

  async exportLessonSummary(conversationId: string): Promise<Blob> {
    // Fallback: Generate a simple text summary if PDF service is not available
    try {
      const { data: conversation } = await supabase
        .from('cleo_conversations')
        .select(`
          *,
          cleo_messages(*)
        `)
        .eq('id', conversationId)
        .single();

      if (!conversation) throw new Error('Conversation not found');

      // Create a simple text summary
      const summary = `
LESSON SUMMARY
==============

Lesson: ${conversation.lesson_id || 'Untitled Lesson'}
Date: ${new Date(conversation.created_at).toLocaleDateString()}
Duration: ${Math.round((new Date(conversation.updated_at).getTime() - new Date(conversation.created_at).getTime()) / 60000)} minutes

CONVERSATION TRANSCRIPT
=======================

${conversation.cleo_messages?.map((msg: any) => 
  `${msg.role === 'user' ? 'You' : 'Cleo'}: ${msg.content}`
).join('\n\n') || 'No messages recorded'}

---
Generated by Cleo AI Tutor
      `.trim();

      return new Blob([summary], { type: 'text/plain' });
    } catch (error) {
      console.error('Error exporting summary:', error);
      throw new Error('Failed to export lesson summary');
    }
  }
};
