import { supabase } from '@/integrations/supabase/client';

export interface LessonExportData {
  lessonTitle: string;
  topic: string;
  yearGroup: string;
  duration: number;
  completedAt: string;
  transcript: string;
  questionsAnswered: number;
  accuracy: number;
  keyPoints: string[];
}

export const lessonExportService = {
  async generateLessonPDF(conversationId: string): Promise<string> {
    try {
      const { data, error } = await supabase.functions.invoke('generate-lesson-pdf', {
        body: { conversationId }
      });

      if (error) throw error;
      if (!data?.pdfUrl) throw new Error('No PDF URL returned');

      return data.pdfUrl;
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw new Error('Failed to generate lesson summary PDF');
    }
  },

  async exportLessonSummary(conversationId: string): Promise<Blob> {
    try {
      const { data: conversation } = await supabase
        .from('cleo_conversations')
        .select(`
          *,
          cleo_messages(*),
          cleo_question_answers(*)
        `)
        .eq('id', conversationId)
        .single();

      if (!conversation) throw new Error('Conversation not found');

      // Calculate metrics
      const messages = conversation.cleo_messages || [];
      const questions = conversation.cleo_question_answers || [];
      const duration = Math.round((new Date(conversation.updated_at).getTime() - new Date(conversation.created_at).getTime()) / 60000);
      const correctAnswers = questions.filter((q: any) => q.is_correct).length;
      const accuracy = questions.length > 0 ? Math.round((correctAnswers / questions.length) * 100) : 0;

      // Create enhanced text summary
      const summary = `
═══════════════════════════════════════
     CLEO AI TUTOR - LESSON REPORT
═══════════════════════════════════════

LESSON DETAILS
--------------
Subject: ${conversation.topic || 'General Learning'}
Date: ${new Date(conversation.created_at).toLocaleDateString('en-US', { 
  weekday: 'long', 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric' 
})}
Duration: ${duration} minutes
Status: ${conversation.status}

PERFORMANCE METRICS
-------------------
Questions Answered: ${questions.length}
Correct Answers: ${correctAnswers}
Accuracy: ${accuracy}%
Messages Exchanged: ${messages.length}

CONVERSATION MODE
-----------------
Voice Duration: ${Math.round((conversation.voice_duration_seconds || 0) / 60)} minutes
Text Messages: ${conversation.text_message_count || 0}
Mode Switches: ${conversation.mode_switches || 0}

LEARNING OBJECTIVES
-------------------
${conversation.learning_goal || 'General comprehension and practice'}

CONVERSATION TRANSCRIPT
=======================

${messages.map((msg: any) => {
  const timestamp = new Date(msg.created_at).toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit' 
  });
  return `[${timestamp}] ${msg.role === 'user' ? 'You' : 'Cleo'}: ${msg.content}`;
}).join('\n\n') || 'No messages recorded'}

QUESTIONS & ANSWERS
===================

${questions.map((q: any, idx: number) => `
Question ${idx + 1}: ${q.question_text}
Your Answer: ${q.answer_text}
Result: ${q.is_correct ? '✓ Correct' : '✗ Incorrect'}
Time Taken: ${q.time_taken_seconds || 0}s
`).join('\n') || 'No questions answered'}

═══════════════════════════════════════
Generated by Cleo AI Tutor
${new Date().toISOString()}
═══════════════════════════════════════
      `.trim();

      return new Blob([summary], { type: 'text/plain' });
    } catch (error) {
      console.error('Error exporting summary:', error);
      throw new Error('Failed to export lesson summary');
    }
  },

  async exportAsJSON(conversationId: string): Promise<Blob> {
    try {
      const { data: conversation } = await supabase
        .from('cleo_conversations')
        .select(`
          *,
          cleo_messages(*),
          cleo_question_answers(*),
          cleo_learning_progress(*)
        `)
        .eq('id', conversationId)
        .single();

      if (!conversation) throw new Error('Conversation not found');

      const exportData = {
        lesson: {
          id: conversation.id,
          topic: conversation.topic,
          subject: conversation.subject_id,
          learningGoal: conversation.learning_goal,
          status: conversation.status,
        },
        session: {
          startTime: conversation.created_at,
          endTime: conversation.updated_at,
          durationMinutes: Math.round((new Date(conversation.updated_at).getTime() - new Date(conversation.created_at).getTime()) / 60000),
          voiceDurationSeconds: conversation.voice_duration_seconds,
          textMessageCount: conversation.text_message_count,
          modeSwitches: conversation.mode_switches,
        },
        messages: conversation.cleo_messages,
        questions: conversation.cleo_question_answers,
        progress: conversation.cleo_learning_progress,
        exportedAt: new Date().toISOString(),
      };

      return new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    } catch (error) {
      console.error('Error exporting JSON:', error);
      throw new Error('Failed to export as JSON');
    }
  },

  async generateLessonExam(conversationId: string): Promise<Blob> {
    try {
      const { data, error } = await supabase.functions.invoke('generate-lesson-exam', {
        body: { conversationId }
      });

      if (error) throw error;
      if (!data?.pdfData) throw new Error('No PDF data returned');

      // Decode base64 PDF data
      const binaryString = atob(data.pdfData);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      
      return new Blob([bytes], { type: 'application/pdf' });
    } catch (error) {
      console.error('Error generating exam PDF:', error);
      throw new Error('Failed to generate lesson exam PDF');
    }
  }
};
