
import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { NetlessService } from '@/services/netlessService';
import { toast } from 'sonner';

interface NetlessCredentials {
  roomUuid: string;
  roomToken: string;
  appIdentifier: string;
}

// The correct Netless App Identifier - always use this
const CORRECT_NETLESS_APP_IDENTIFIER = 'TORbYEt7EfCzGuPZ97oCJA/9M23Doi-qTMNAg';

export const useNetlessCredentials = (lessonId: string, userRole: 'tutor' | 'student') => {
  const [credentials, setCredentials] = useState<NetlessCredentials | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!lessonId) {
      console.log('useNetlessCredentials: No lesson ID provided');
      setIsLoading(false);
      return;
    }
    loadCredentials();
  }, [lessonId, userRole]);

  const loadCredentials = async () => {
    try {
      setIsLoading(true);
      setError(null);

      console.log('useNetlessCredentials: Loading credentials for lesson:', lessonId, 'role:', userRole);

      // Fetch lesson data to get existing Netless credentials
      const { data: lessonData, error: lessonError } = await supabase
        .from('lessons')
        .select('netless_room_uuid, netless_room_token, netless_app_identifier')
        .eq('id', lessonId)
        .single();

      if (lessonError) {
        console.error('useNetlessCredentials: Failed to fetch lesson data:', lessonError);
        throw new Error('Failed to fetch lesson data');
      }

      console.log('useNetlessCredentials: Lesson whiteboard data:', {
        hasRoomUuid: !!lessonData.netless_room_uuid,
        hasAppIdentifier: !!lessonData.netless_app_identifier,
        hasRoomToken: !!lessonData.netless_room_token,
        roomUuid: lessonData.netless_room_uuid ? lessonData.netless_room_uuid.substring(0, 8) + '...' : 'null',
        storedAppId: lessonData.netless_app_identifier ? lessonData.netless_app_identifier.substring(0, 8) + '...' : 'null'
      });

      // Check if we have room UUID and room token
      if (lessonData.netless_room_uuid && lessonData.netless_room_token) {
        console.log('useNetlessCredentials: Using existing credentials with correct app identifier');
        
        // Always use the correct app identifier, regardless of what's stored in the database
        const creds = {
          roomUuid: lessonData.netless_room_uuid,
          roomToken: lessonData.netless_room_token,
          appIdentifier: CORRECT_NETLESS_APP_IDENTIFIER // Always use the correct one
        };
        
        // Update the database with the correct app identifier if it's wrong
        if (lessonData.netless_app_identifier !== CORRECT_NETLESS_APP_IDENTIFIER) {
          console.log('useNetlessCredentials: Updating database with correct app identifier');
          await supabase
            .from('lessons')
            .update({ netless_app_identifier: CORRECT_NETLESS_APP_IDENTIFIER })
            .eq('id', lessonId);
        }
        
        setCredentials(creds);
        console.log('useNetlessCredentials: Credentials set successfully with correct app identifier');
      } else {
        console.log('useNetlessCredentials: Missing room UUID or token, credentials will be generated by server');
        setError('Whiteboard credentials need to be generated');
      }
    } catch (err) {
      console.error('useNetlessCredentials: Error loading credentials:', err);
      setError(err instanceof Error ? err.message : 'Failed to load whiteboard configuration');
    } finally {
      setIsLoading(false);
    }
  };

  const regenerateToken = async () => {
    if (!credentials) {
      console.log('useNetlessCredentials: No credentials to regenerate, reloading...');
      await loadCredentials();
      return;
    }

    try {
      console.log('useNetlessCredentials: Regenerating token...');
      toast.info('Regenerating whiteboard token...');
      await loadCredentials();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to regenerate whiteboard token');
    }
  };

  return {
    credentials,
    isLoading,
    error,
    regenerateToken
  };
};
