
import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { NetlessService } from '@/services/netlessService';
import { toast } from 'sonner';

interface NetlessCredentials {
  roomUuid: string;
  roomToken: string;
  appIdentifier: string;
}

export const useNetlessCredentials = (lessonId: string, userRole: 'tutor' | 'student') => {
  const [credentials, setCredentials] = useState<NetlessCredentials | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!lessonId) {
      setIsLoading(false);
      return;
    }
    loadCredentials();
  }, [lessonId, userRole]);

  const loadCredentials = async () => {
    try {
      setIsLoading(true);
      setError(null);

      console.log('Loading Netless credentials for lesson:', lessonId);

      // Fetch lesson data to get existing Netless credentials
      const { data: lessonData, error: lessonError } = await supabase
        .from('lessons')
        .select('netless_room_uuid, netless_room_token, netless_app_identifier')
        .eq('id', lessonId)
        .single();

      if (lessonError) {
        console.error('Failed to fetch lesson data:', lessonError);
        throw new Error('Failed to fetch lesson data');
      }

      console.log('Lesson whiteboard data:', lessonData);

      // Check if we have all required credentials
      if (lessonData.netless_room_uuid && lessonData.netless_app_identifier && lessonData.netless_room_token) {
        console.log('Using existing Netless credentials');
        setCredentials({
          roomUuid: lessonData.netless_room_uuid,
          roomToken: lessonData.netless_room_token,
          appIdentifier: lessonData.netless_app_identifier
        });
      } else if (lessonData.netless_room_uuid && lessonData.netless_app_identifier) {
        console.log('Missing room token, will be regenerated by server');
        // Token will be regenerated by the agora-integration edge function
        setError('Whiteboard token needs to be regenerated');
      } else {
        console.log('No whiteboard configuration found');
        setError('Whiteboard not configured for this lesson');
      }
    } catch (err) {
      console.error('Error loading Netless credentials:', err);
      setError(err instanceof Error ? err.message : 'Failed to load whiteboard configuration');
    } finally {
      setIsLoading(false);
    }
  };

  const regenerateToken = async () => {
    if (!credentials) {
      console.log('No credentials to regenerate, reloading...');
      await loadCredentials();
      return;
    }

    try {
      console.log('Regenerating Netless token...');
      toast.info('Regenerating whiteboard token...');
      await loadCredentials();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to regenerate whiteboard token');
    }
  };

  return {
    credentials,
    isLoading,
    error,
    regenerateToken
  };
};
