import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.5";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Validate text block data structure
function validateBlockData(data: any): boolean {
  return data && typeof data === 'object' && typeof data.text === 'string' && data.text.length > 0;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const lovableApiKey = Deno.env.get('LOVABLE_API_KEY')!;

    const supabase = createClient(supabaseUrl, supabaseKey);

    const authHeader = req.headers.get('Authorization')!;
    const token = authHeader.replace('Bearer ', '');
    const { data: { user } } = await supabase.auth.getUser(token);

    if (!user) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized - Please sign in to generate lesson plans' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const { lessonId, topic, yearGroup, learningGoal, conversationId } = await req.json();

    console.log('Generating lesson plan:', { lessonId, topic, yearGroup, learningGoal });

    // Validate lessonId against lessons table to avoid FK violations
    let lessonIdToInsert: string | null = null;
    if (lessonId) {
      const { data: existingLesson, error: lessonCheckError } = await supabase
        .from('lessons')
        .select('id')
        .eq('id', lessonId)
        .single();
      if (lessonCheckError) {
        console.warn('Lesson check error (continuing without linking lesson):', lessonCheckError.message);
      }
      if (existingLesson?.id) {
        lessonIdToInsert = existingLesson.id;
      } else {
        console.log('Provided lessonId not found, proceeding with null linkage');
      }
    }

    // Check for existing lesson plan BEFORE creating a new one
    let existingPlan;

    if (lessonIdToInsert) {
      // Check by lesson_id for lesson-based plans
      const { data } = await supabase
        .from('cleo_lesson_plans')
        .select('id, status')
        .eq('lesson_id', lessonIdToInsert)
        .maybeSingle();
      existingPlan = data;
      console.log('Checked for existing plan by lesson_id:', lessonIdToInsert, 'found:', !!data);
    } else {
      // Check by topic + year_group for standalone plans
      const { data } = await supabase
        .from('cleo_lesson_plans')
        .select('id, status')
        .eq('topic', topic)
        .eq('year_group', yearGroup)
        .is('lesson_id', null)
        .maybeSingle();
      existingPlan = data;
      console.log('Checked for existing plan by topic/year_group:', topic, yearGroup, 'found:', !!data);
    }

    // If plan exists and is ready, return it immediately
    if (existingPlan && existingPlan.status === 'ready') {
      console.log('📚 Using existing lesson plan:', existingPlan.id);
      return new Response(
        JSON.stringify({ 
          lessonPlanId: existingPlan.id,
          isExisting: true 
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // If plan exists but is still generating, return it (client will wait)
    if (existingPlan && existingPlan.status === 'generating') {
      console.log('⏳ Plan is being generated by another request:', existingPlan.id);
      return new Response(
        JSON.stringify({ 
          lessonPlanId: existingPlan.id,
          isGenerating: true 
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // No existing plan found, create a new one
    console.log('📝 Creating new lesson plan for:', topic, yearGroup);

    // Create lesson plan record
    const { data: lessonPlan, error: planError } = await supabase
      .from('cleo_lesson_plans')
      .insert({
        lesson_id: lessonIdToInsert,
        conversation_id: conversationId,
        topic,
        year_group: yearGroup,
        status: 'generating'
      })
      .select()
      .single();

    if (planError) throw planError;

    // Generate lesson plan using Lovable AI
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${lovableApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'openai/gpt-5-mini',
        messages: [
          {
            role: 'system',
            content: `You are an expert teacher creating clear, simple lesson plans for students.

Create a lesson plan with:
1. Learning Objectives (3-5 clear, measurable goals)
2. Teaching Steps (5-8 text sections covering key concepts)

Each teaching step should have:
- A clear, descriptive title
- Simple text content (2-4 paragraphs of explanation)
- Age-appropriate language for ${yearGroup}

Focus on explaining concepts clearly with well-structured paragraphs that build understanding progressively.`
          },
          {
            role: 'user',
            content: `Create a clear, simple lesson plan for: ${topic}
Year Group: ${yearGroup}
${learningGoal ? `Learning Goal: ${learningGoal}` : ''}

Generate 5-8 text sections that explain the key concepts clearly.`
          }
        ],
        tools: [{
          type: 'function',
          function: {
            name: 'create_lesson_plan',
            description: 'Create a simple text-based lesson plan',
            parameters: {
              type: 'object',
              properties: {
                objectives: {
                  type: 'array',
                  items: { type: 'string' },
                  description: '3-5 clear learning objectives'
                },
                steps: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: { type: 'string', description: 'Unique identifier for this step' },
                      title: { type: 'string', description: 'Clear title for this teaching section' },
                      content: { type: 'string', description: 'Text content explaining the concept (2-4 paragraphs)' }
                    },
                    required: ['id', 'title', 'content']
                  },
                  description: '5-8 teaching steps with text content'
                }
              },
              required: ['objectives', 'steps']
            }
          }
        }],
        tool_choice: { type: 'function', function: { name: 'create_lesson_plan' } }
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI API error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limits exceeded. Please try again later.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ error: 'Payment required. Please add Lovable AI credits to your workspace.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`AI API failed: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log('AI response received');

    const toolCall = aiData.choices[0].message.tool_calls?.[0];
    if (!toolCall) {
      throw new Error('No lesson plan generated');
    }

    const planData = JSON.parse(toolCall.function.arguments);
    console.log('Parsed plan data:', { 
      objectives: planData.objectives.length,
      steps: planData.steps.length 
    });

    // Update lesson plan with objectives and sequence
    const { error: updateError } = await supabase
      .from('cleo_lesson_plans')
      .update({
        learning_objectives: planData.objectives,
        teaching_sequence: planData.steps.map((s: any) => ({
          id: s.id,
          title: s.title,
          duration_minutes: s.duration_minutes
        })),
        status: 'ready'
      })
      .eq('id', lessonPlan.id);

    if (updateError) throw updateError;

    // Insert text content blocks
    const contentBlocks: any[] = [];

    planData.steps.forEach((step: any, index: number) => {
      const blockData = { text: step.content };
      
      // Validate content is not empty
      if (!validateBlockData(blockData)) {
        console.warn(`Empty or invalid content for step ${step.id}, skipping`);
        return;
      }

      contentBlocks.push({
        lesson_plan_id: lessonPlan.id,
        block_type: 'text',
        sequence_order: index,
        step_id: step.id,
        title: step.title,
        data: blockData,
        teaching_notes: '',
        prerequisites: []
      });
    });

    console.log(`Generated ${contentBlocks.length} valid content blocks`);

    if (contentBlocks.length > 0) {
      const { error: blocksError } = await supabase
        .from('lesson_content_blocks')
        .insert(contentBlocks);

      if (blocksError) throw blocksError;
    }

    console.log('Lesson plan created successfully:', lessonPlan.id);

    return new Response(
      JSON.stringify({ 
        lessonPlanId: lessonPlan.id,
        objectives: planData.objectives,
        stepsCount: planData.steps.length,
        contentBlocksCount: contentBlocks.length
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error generating lesson plan:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});