
-- Insert GCSE Maths Foundation lesson plans
INSERT INTO lesson_plans (subject, term, week_number, topic_title, description) VALUES
-- Term 1: Autumn (Weeks 1-13)
('GCSE Maths Foundation', 'Term 1: Autumn', 1, 'Number Fundamentals', 'Number operations'),
('GCSE Maths Foundation', 'Term 1: Autumn', 2, 'Number Fundamentals', 'Factors, multiples, and primes. Introduction to standard form & indices'),
('GCSE Maths Foundation', 'Term 1: Autumn', 3, 'Intro to Algebra', 'Simplifying algebraic expressions'),
('GCSE Maths Foundation', 'Term 1: Autumn', 4, 'Intro to Algebra', 'Understanding algebraic notation. Solving linear equations'),
('GCSE Maths Foundation', 'Term 1: Autumn', 5, 'Ratio & Proportion Basics', 'Understanding ratios'),
('GCSE Maths Foundation', 'Term 1: Autumn', 6, 'Ratio & Proportion Basics', 'Proportional relationships. Speed, density, and other rates of change'),
('GCSE Maths Foundation', 'Term 1: Autumn', 7, 'Geometry Basics', 'Geometric shapes and their properties'),
('GCSE Maths Foundation', 'Term 1: Autumn', 8, 'Geometry Basics', 'Perimeter, area, and volume. Angles in polygons'),
('GCSE Maths Foundation', 'Term 1: Autumn', 9, 'Intro to Data & Probability', 'Collecting and representing data'),
('GCSE Maths Foundation', 'Term 1: Autumn', 10, 'Intro to Data & Probability', 'Measures of central tendency. Basic probability concepts'),
('GCSE Maths Foundation', 'Term 1: Autumn', 11, 'Coordinate Geometry', 'Plotting points'),
('GCSE Maths Foundation', 'Term 1: Autumn', 12, 'Coordinate Geometry', 'Drawing and interpreting linear graphs. Understanding gradient and intercepts'),
('GCSE Maths Foundation', 'Term 1: Autumn', 13, 'Term 1 Exam & Feedback', 'Mixed-topic assessment covering weeks 1-12. Error analysis and feedback'),

-- Term 2: Spring (Weeks 14-26)
('GCSE Maths Foundation', 'Term 2: Spring', 14, 'FDP Applications', 'Convert between fractions, decimals, percentages'),
('GCSE Maths Foundation', 'Term 2: Spring', 15, 'FDP Applications', 'Percentage increase/decrease. Profit, loss, tax problems'),
('GCSE Maths Foundation', 'Term 2: Spring', 16, 'Quadratics & Sequences', 'Solving quadratics: factorising, completing square, quadratic formula'),
('GCSE Maths Foundation', 'Term 2: Spring', 17, 'Quadratics & Sequences', 'Algebraic fractions. Recognising and generating sequences (arithmetic & geometric)'),
('GCSE Maths Foundation', 'Term 2: Spring', 18, 'Ratio & Proportion Advanced', 'Scale factors and map scaling'),
('GCSE Maths Foundation', 'Term 2: Spring', 19, 'Ratio & Proportion Advanced', 'Direct and inverse proportion. Proportion in real-life problems'),
('GCSE Maths Foundation', 'Term 2: Spring', 20, 'Transformations & Circle Theorems', 'Translations, rotations, reflections, enlargements'),
('GCSE Maths Foundation', 'Term 2: Spring', 21, 'Transformations & Circle Theorems', 'Congruence and similarity. Circle theorems: cyclic quadrilaterals, tangents'),
('GCSE Maths Foundation', 'Term 2: Spring', 22, 'Data & Probability Analysis', 'Interpreting bar charts, pie charts, histograms'),
('GCSE Maths Foundation', 'Term 2: Spring', 23, 'Data & Probability Analysis', 'Independent and dependent probability. Cumulative frequency, box plots'),
('GCSE Maths Foundation', 'Term 2: Spring', 24, 'Inequalities & Simultaneous Equations', 'Solve and graph inequalities'),
('GCSE Maths Foundation', 'Term 2: Spring', 25, 'Inequalities & Simultaneous Equations', 'Solve simultaneous equations (algebraically & graphically)'),
('GCSE Maths Foundation', 'Term 2: Spring', 26, 'Term 2 Exam & Feedback', 'Mixed-topic assessment covering weeks 14-25. Error analysis and feedback'),

-- Term 3: Summer (Weeks 27-39)
('GCSE Maths Foundation', 'Term 3: Summer', 27, 'Advanced Number & Estimation', 'Standard form in calculations'),
('GCSE Maths Foundation', 'Term 3: Summer', 28, 'Advanced Number & Estimation', 'Error bounds. Real-world numerical problems'),
('GCSE Maths Foundation', 'Term 3: Summer', 29, 'Higher Algebra & Functions', 'Further manipulation (expanding, factorising complex expressions)'),
('GCSE Maths Foundation', 'Term 3: Summer', 30, 'Higher Algebra & Functions', 'Graphing functions. Introduction to exponential functions'),
('GCSE Maths Foundation', 'Term 3: Summer', 31, 'Ratio & Financial Maths', 'Advanced rate problems'),
('GCSE Maths Foundation', 'Term 3: Summer', 32, 'Ratio & Financial Maths', 'Ratio in geometric contexts. Simple and compound interest'),
('GCSE Maths Foundation', 'Term 3: Summer', 33, 'Trigonometry & Vectors', 'Sine and cosine rules'),
('GCSE Maths Foundation', 'Term 3: Summer', 34, 'Trigonometry & Vectors', 'Solving non-right-angled triangles. Vector geometry: addition, subtraction, scalar multiplication'),
('GCSE Maths Foundation', 'Term 3: Summer', 35, 'Statistics & Probability Advanced', 'Conditional probability'),
('GCSE Maths Foundation', 'Term 3: Summer', 36, 'Statistics & Probability Advanced', 'Correlation and regression. Advanced data interpretation'),
('GCSE Maths Foundation', 'Term 3: Summer', 37, 'Term 3 Exam & Feedback', 'Assessment across Term 3 content. Feedback and remediation'),

-- Term 4: Final Consolidation (Weeks 40-52)
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 40, 'Algebra & Number Review', 'Address common misconceptions'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 41, 'Algebra & Number Review', 'Algebra & Number review'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 42, 'Geometry & Ratio/Proportion Revision', 'Targeted practice papers'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 43, 'Geometry & Ratio/Proportion Revision', 'Geometry & Ratio/Proportion revision'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 44, 'Data Handling & Probability Revision', 'Past paper practice'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 45, 'Data Handling & Probability Revision', 'Data handling & probability revision'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 46, 'Trigonometry & Vectors Recap', 'Mixed-topic exam drills'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 47, 'Trigonometry & Vectors Recap', 'Trigonometry & vectors recap'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 48, 'Mock Exam Week', 'Full Paper 1 and Paper 2 style. Marking & feedback sessions'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 49, 'Mock Exam Week', 'Mock Exam Week'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 50, 'Individualised Revision', 'Final focus on weakest areas (based on mocks)'),
('GCSE Maths Foundation', 'Term 4: Final Consolidation', 51, 'Individualised Revision', 'Individualised revision tasks'),

-- Insert GCSE Maths Higher lesson plans
-- Section 1: Weeks 1-13 — Number & Algebra Foundations
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 1, 'Place Value & Rounding', 'Place value & rounding'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 2, 'Four Operations', 'Four operations with integers and decimals'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 3, 'BIDMAS', 'BIDMAS'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 4, 'Estimation & Error Bounds', 'Estimation and error bounds'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 5, 'Indices', 'Indices & laws of indices'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 6, 'Standard Form', 'Introduction to standard form'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 7, 'Surds', 'Surds and their properties'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 8, 'Surds Advanced', 'Simplifying and rationalising surds'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 9, 'Intro to Algebra', 'Introduction to algebra: expressions and simplification'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 10, 'Single Brackets', 'Expanding and factorising single brackets'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 11, 'Quadratics', 'Expanding and factorising quadratics'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 12, 'Difference of Squares', 'Difference of squares'),
('GCSE Maths Higher', 'Section 1: Number & Algebra Foundations', 13, 'Linear Equations', 'Solving linear equations and inequalities'),

-- Section 2: Weeks 14-26 — Algebra, Sequences & Geometry
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 14, 'Quadratic Equations', 'Solving quadratic equations (factorising, completing the square)'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 15, 'Quadratic Formula', 'Quadratic formula'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 16, 'Algebraic Fractions', 'Algebraic fractions'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 17, 'FDP Conversions', 'Fractions, decimals, percentages conversions'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 18, 'FDP Calculations', 'FDP calculations incl. compound interest'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 19, 'Sequences', 'Arithmetic and geometric sequences'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 20, 'Sequence Applications', 'nth term and applications'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 21, 'Series', 'Series: sum formulas (arithmetic & geometric)'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 22, 'Recursive Sequences', 'Recursive sequences'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 23, 'Graph Functions', 'Graphs of linear and quadratic functions'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 24, 'Transformations of Graphs', 'Transformations of graphs'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 25, 'Coordinate Geometry', 'Coordinate geometry (gradients, equations of lines)'),
('GCSE Maths Higher', 'Section 2: Algebra, Sequences & Geometry', 26, 'Real-world Applications', 'Real-world applications of number'),

-- Section 3: Weeks 27-39 — Proportion, Advanced Algebra, Trigonometry, Statistics
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 27, 'Proportion', 'Direct and inverse proportion'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 28, 'Speed-Distance-Time', 'Ratio problems and speed-distance-time'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 29, 'Rates of Change', 'Rates of change'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 30, 'Financial Maths', 'Financial maths: compound interest, annuities'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 31, 'Simultaneous Equations', 'Simultaneous equations (linear & linear/quadratic)'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 32, 'Real-life Applications', 'Application to real-life problems'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 33, 'Partial Fractions', 'Partial fractions'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 34, 'Functions', 'Composite and inverse functions'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 35, 'Circle Theorems', 'Circle theorems'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 36, 'Basic Trigonometry', 'Basic trigonometry (SOHCAHTOA)'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 37, 'Sine & Cosine Rules', 'Sine & Cosine rules'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 38, 'Angles of Elevation', 'Angles of elevation and depression'),
('GCSE Maths Higher', 'Section 3: Proportion, Advanced Algebra, Trigonometry', 39, 'Vectors', 'Vector operations (addition, subtraction, scalar multiplication)'),

-- Section 4: Weeks 40-52 — Higher-Level Topics, Statistics & Revision
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 40, 'Probability', 'Probability (independent/dependent events)'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 41, 'Venn Diagrams', 'Venn diagrams and conditional probability'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 42, 'Data Representation', 'Data representation: histograms, box plots'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 43, 'Central Tendency', 'Measures of central tendency and dispersion'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 44, 'Standard Deviation', 'Standard deviation'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 45, 'Hypothesis Testing', 'Hypothesis testing and statistical inference'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 46, 'Advanced Geometry', 'Advanced coordinate geometry (parabolas, hyperbolas)'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 47, '3D Geometry', '3D geometry and solids'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 48, 'Complex Numbers', 'Complex number operations (if applicable for extension students)'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 49, 'Real-world Applications', 'Real-world number and algebra applications'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 50, 'Review & Gap Closing', 'Review across all major topics. Identify and close gaps'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 51, 'Past Papers', 'Past paper practice & exam strategy'),
('GCSE Maths Higher', 'Section 4: Higher-Level Topics, Statistics & Revision', 52, 'Final Consolidation', 'Final consolidation'),

-- Insert GCSE Combined Science lesson plans
-- Autumn Term: Weeks 1-12
('GCSE Combined Science', 'Autumn Term', 1, 'Cell Biology & Organisation', 'Cell structure (animal, plant, bacterial). Specialised cells and microscopy'),
('GCSE Combined Science', 'Autumn Term', 2, 'Cell Biology & Organisation', 'Cell division: mitosis, meiosis. Organisation: tissues → organs → systems'),
('GCSE Combined Science', 'Autumn Term', 3, 'Atomic Structure & Periodic Table', 'Protons, neutrons, electrons. Electron configuration & isotopes'),
('GCSE Combined Science', 'Autumn Term', 4, 'Atomic Structure & Periodic Table', 'Development of the periodic table. Trends in groups & periods'),
('GCSE Combined Science', 'Autumn Term', 5, 'Energy', 'Energy stores, systems, and transfers'),
('GCSE Combined Science', 'Autumn Term', 6, 'Energy', 'Calculations: work done, power, efficiency. Renewable vs non-renewable sources'),
('GCSE Combined Science', 'Autumn Term', 7, 'Infection and Response', 'Types of pathogens: bacteria, viruses, fungi, protists'),
('GCSE Combined Science', 'Autumn Term', 8, 'Infection and Response', 'Immune system: white blood cells, antibodies. Vaccination, antibiotics, resistance. Drug development and clinical trials'),
('GCSE Combined Science', 'Autumn Term', 9, 'Bonding, Structure & Properties', 'Ionic, covalent, and metallic bonding'),
('GCSE Combined Science', 'Autumn Term', 10, 'Bonding, Structure & Properties', 'States of matter & structure–property links. Simple vs giant covalent structures. Intro to intermolecular forces'),
('GCSE Combined Science', 'Autumn Term', 11, 'Electricity', 'Current, voltage, resistance. Ohm\'s law and circuit calculations'),
('GCSE Combined Science', 'Autumn Term', 12, 'Electricity', 'Series and parallel circuits'),

-- Spring Term: Weeks 13-24
('GCSE Combined Science', 'Spring Term', 13, 'Bioenergetics & Homeostasis', 'Photosynthesis and limiting factors'),
('GCSE Combined Science', 'Spring Term', 14, 'Bioenergetics & Homeostasis', 'Aerobic vs anaerobic respiration. Homeostasis: blood sugar, water, temperature'),
('GCSE Combined Science', 'Spring Term', 15, 'Quantitative Chemistry & Chemical Changes', 'Moles, Mr, % composition'),
('GCSE Combined Science', 'Spring Term', 16, 'Quantitative Chemistry & Chemical Changes', 'Reacting masses and limiting reactants. Acids, alkalis, pH scale. Neutralisation, reactivity series, and displacement'),
('GCSE Combined Science', 'Spring Term', 17, 'Forces and Motion', 'Types of forces (contact, non-contact). Newton\'s Laws'),
('GCSE Combined Science', 'Spring Term', 18, 'Forces and Motion', 'Motion graphs, distance-time & velocity-time'),
('GCSE Combined Science', 'Spring Term', 19, 'Genetics & Evolution', 'DNA, genes, chromosomes'),
('GCSE Combined Science', 'Spring Term', 20, 'Genetics & Evolution', 'Inheritance: alleles, Punnett squares. Evolution, natural selection, fossils'),
('GCSE Combined Science', 'Spring Term', 21, 'Energy Changes & Rates of Reaction', 'Exothermic vs endothermic reactions. Energy profile diagrams'),
('GCSE Combined Science', 'Spring Term', 22, 'Energy Changes & Rates of Reaction', 'Rates of reaction: temperature, concentration, catalysts'),
('GCSE Combined Science', 'Spring Term', 23, 'Waves', 'Types of waves: transverse, longitudinal. Wave speed equation'),
('GCSE Combined Science', 'Spring Term', 24, 'Waves', 'Reflection, refraction, sound'),

-- Summer Term: Weeks 25-36
('GCSE Combined Science', 'Summer Term', 25, 'Ecology & Plant Biology', 'Ecosystems, food chains/webs'),
('GCSE Combined Science', 'Summer Term', 26, 'Ecology & Plant Biology', 'Biodiversity and human impact. Plant transport: xylem, phloem. Reproduction and hormones in plants'),
('GCSE Combined Science', 'Summer Term', 27, 'Organic Chemistry & Analysis', 'Alkanes, alkenes, combustion'),
('GCSE Combined Science', 'Summer Term', 28, 'Organic Chemistry & Analysis', 'Alcohols, carboxylic acids, esters. Flame tests, chromatography. Instrumental analysis (IR, MS overview)'),
('GCSE Combined Science', 'Summer Term', 29, 'Magnetism and Electromagnetism', 'Magnets and fields'),
('GCSE Combined Science', 'Summer Term', 30, 'Magnetism and Electromagnetism', 'Electromagnets and induction. Applications: motors, transformers'),
('GCSE Combined Science', 'Summer Term', 31, 'Health and Disease', 'Non-communicable diseases (e.g., cancer, CHD)'),
('GCSE Combined Science', 'Summer Term', 32, 'Health and Disease', 'Lifestyle and genetic risks. Epidemiology and data interpretation'),
('GCSE Combined Science', 'Summer Term', 33, 'Atmosphere & Earth\'s Resources', 'Evolution of Earth\'s atmosphere'),
('GCSE Combined Science', 'Summer Term', 34, 'Atmosphere & Earth\'s Resources', 'Greenhouse gases & climate change. Recycling, finite vs renewable resources'),
('GCSE Combined Science', 'Summer Term', 35, 'Mid-Year Exam Preparation', 'Mixed-topic assessments'),
('GCSE Combined Science', 'Summer Term', 36, 'Mid-Year Exam Preparation', 'Targeted revision & practice. Time management, interpreting mark schemes'),

-- Extended Curriculum: Weeks 37-52
('GCSE Combined Science', 'Extended Curriculum', 37, 'Retrieval Week – Biology Focus', 'Knowledge organisers & quizzes on key topics'),
('GCSE Combined Science', 'Extended Curriculum', 38, 'Retrieval Week – Biology Focus', 'Recap: Cells, Infection, Bioenergetics, Genetics'),
('GCSE Combined Science', 'Extended Curriculum', 39, 'Retrieval Week – Chemistry Focus', 'Recap: Atoms, Bonding, Quantitative Chemistry'),
('GCSE Combined Science', 'Extended Curriculum', 40, 'Retrieval Week – Chemistry Focus', 'Exam-style questions + feedback'),
('GCSE Combined Science', 'Extended Curriculum', 41, 'Retrieval Week – Physics Focus', 'Recap: Energy, Forces, Waves'),
('GCSE Combined Science', 'Extended Curriculum', 42, 'Retrieval Week – Physics Focus', 'Practice calculations and data interpretation'),
('GCSE Combined Science', 'Extended Curriculum', 43, 'Advanced Genetics & Inheritance', 'Genetic disorders'),
('GCSE Combined Science', 'Extended Curriculum', 44, 'Advanced Genetics & Inheritance', 'Genetic engineering (GM crops, cloning, ethics)'),
('GCSE Combined Science', 'Extended Curriculum', 45, 'Chemical Industry & Practical Techniques', 'Titrations (core practical)'),
('GCSE Combined Science', 'Extended Curriculum', 46, 'Chemical Industry & Practical Techniques', 'Making salts. Industrial processes: Haber, Contact process'),
('GCSE Combined Science', 'Extended Curriculum', 47, 'Space Physics', 'Life cycle of stars'),
('GCSE Combined Science', 'Extended Curriculum', 48, 'Space Physics', 'Solar system, red shift. Universe expansion & evidence'),
('GCSE Combined Science', 'Extended Curriculum', 49, 'Project & Investigation Week', 'Independent science project. Collecting and analysing data'),
('GCSE Combined Science', 'Extended Curriculum', 50, 'Project & Investigation Week', 'Presenting findings (poster or presentation)'),
('GCSE Combined Science', 'Extended Curriculum', 51, 'Final Review & Exam Technique', 'Full mocks & feedback'),
('GCSE Combined Science', 'Extended Curriculum', 52, 'Final Review & Exam Technique', 'Strategic revision. Targeted improvement (using question-level analysis)'),

-- Insert GCSE English lesson plans
-- Autumn Term: Weeks 1-16
('GCSE English', 'Autumn Term', 1, 'Intro to GCSE English Language', 'Paper 1 overview (fiction reading & exam format). Intro to GCSE English Literature: Set texts overview & course themes'),
('GCSE English', 'Autumn Term', 2, 'Paper 1 Q1 & Literature Opening Scenes', 'Identifying & interpreting explicit info. Opening scenes/chapters analysis (setting, character, theme)'),
('GCSE English', 'Autumn Term', 3, 'Paper 1 Q2 & Key Characters', 'Language analysis (similes, metaphors, tone). Exploring key characters: introduction & development'),
('GCSE English', 'Autumn Term', 4, 'Paper 1 Q3 & Contextual Influences', 'Structure analysis (narrative sequencing). Contextual influences on literature (historical, social)'),
('GCSE English', 'Autumn Term', 5, 'Paper 1 Q4 & Poetry Introduction', 'Critical evaluation of effects. Poetry Anthology introduction: theme, structure, language'),
('GCSE English', 'Autumn Term', 6, 'Paper 1 Q5 & Poetic Techniques', 'Descriptive writing practice (figurative language). Poetry Anthology: poetic techniques (imagery, tone, form)'),
('GCSE English', 'Autumn Term', 7, 'Paper 2 Q1 & Q2 & Set Text Symbolism', 'Comparing nonfiction texts (summarise & synthesise). Set texts: symbolism and themes'),
('GCSE English', 'Autumn Term', 8, 'Paper 2 Q3 & Character Relationships', 'Language analysis in nonfiction. Set texts: character relationships & plot development'),
('GCSE English', 'Autumn Term', 9, 'Paper 2 Q4 & Unseen Poetry', 'Comparing viewpoints and attitudes. Unseen poetry: introduction to analysis techniques'),
('GCSE English', 'Autumn Term', 10, 'Paper 2 Q5 & Poetry Comparison', 'Writing to argue/persuade (rhetorical devices). Poetry Anthology: comparing two poems by theme & technique'),
('GCSE English', 'Autumn Term', 11, 'Paper 1 Revision & Character Study', 'Paper 1 Q1-Q4 Revision (timed practice). Set texts: detailed character study'),
('GCSE English', 'Autumn Term', 12, 'Paper 2 Revision & Poetry Comparison', 'Paper 2 Q1-Q5 Revision (timed practice). Poetry Anthology: final poem comparison (tone, language, form)'),
('GCSE English', 'Autumn Term', 13, 'Advanced Q2 & Q3 & Conflict Exploration', 'Advanced Q2 & Q3 recap (complex language & structure analysis). Set texts: conflict & resolution exploration'),
('GCSE English', 'Autumn Term', 14, 'Advanced Q4 & Contextual Impact', 'Advanced Q4 critical evaluation. Set texts: contextual impact on characters'),
('GCSE English', 'Autumn Term', 15, 'Advanced Paper 2 & Unseen Poetry', 'Paper 2 Q4 & Q5 advanced (viewpoints & argument). Unseen poetry: further practice & analysis'),
('GCSE English', 'Autumn Term', 16, 'Term Review & Essay Writing', 'Language & Literature: End-of-term review & consolidation. Literature: full critical essay writing practice'),

-- Spring Term: Weeks 17-32
('GCSE English', 'Spring Term', 17, 'Timed Practice & Thematic Comparison', 'Paper 1 & 2 full timed practice. Poetry Anthology: thematic comparison'),
('GCSE English', 'Spring Term', 18, 'Timed Practice & Thematic Essays', 'Paper 1 & 2 full timed practice. Set texts: thematic essay writing'),
('GCSE English', 'Spring Term', 19, 'Creative Writing & Unseen Poetry', 'Paper 1 Q5: Creative writing prompts. Unseen poetry revision'),
('GCSE English', 'Spring Term', 20, 'Language for Persuasion & Key Quotes', 'Paper 2 Q3: Language for persuasion refinement. Set texts: key quotes & themes revision'),
('GCSE English', 'Spring Term', 21, 'Timed Practice & Comparative Essays', 'Paper 1 & 2 full timed practice. Comparative poetry essay writing'),
('GCSE English', 'Spring Term', 22, 'Mock Exams', 'Mock exams Paper 1 (Language) & Paper 1 (Literature)'),
('GCSE English', 'Spring Term', 23, 'Mock Feedback & Thematic Review', 'Mock exams feedback and targeted revision. Set texts: thematic review & essay planning'),
('GCSE English', 'Spring Term', 24, 'Extended Writing & Poetry Revision', 'Paper 2 Q5: Writing to argue & persuade (extended). Poetry anthology: revision of key poems'),
('GCSE English', 'Spring Term', 25, 'Mixed Skills Revision & Character Analysis', 'Paper 1 & 2 timed practice: focused question revision. Set texts: character analysis & context'),
('GCSE English', 'Spring Term', 26, 'Reading Skills & Unseen Poetry', 'Paper 1 Q1-Q4 mixed skills revision. Unseen poetry: timed practice'),
('GCSE English', 'Spring Term', 27, 'Writing Skills & Technique Review', 'Paper 2 Q1-Q5 mixed skills revision. Poetry anthology: technique & language review'),
('GCSE English', 'Spring Term', 28, 'Creative Writing & Essay Planning', 'Extended creative writing practice with peer feedback. Set texts: essay planning & writing'),
('GCSE English', 'Spring Term', 29, 'Non-fiction Comparison & Unseen Poetry', 'Non-fiction comparison practice. Unseen poetry: final practice'),
('GCSE English', 'Spring Term', 30, 'Argumentative Writing & Essay Refinement', 'Writing to argue and persuade practice. Set texts: essay writing refinement'),
('GCSE English', 'Spring Term', 31, 'Paper 1 Practice & Comparative Essays', 'Paper 1 full exam practice. Poetry anthology: timed comparative essay'),
('GCSE English', 'Spring Term', 32, 'Paper 2 Practice & Theme Analysis', 'Paper 2 full exam practice. Set texts: final review & key theme analysis'),

-- Summer Term: Weeks 33-48
('GCSE English', 'Summer Term', 33, 'Final Paper 1 Review & Set Text Revision', 'Final review: Paper 1 Reading Q1–Q4. Set texts: revision of key scenes & themes'),
('GCSE English', 'Summer Term', 34, 'Final Paper 2 Review & Poetry Review', 'Final review: Paper 2 Writing skills Q5. Poetry anthology: final review of structure & themes'),
('GCSE English', 'Summer Term', 35, 'Timed Writing & Character Revision', 'Timed creative writing & argument practice. Set texts: detailed character and theme revision'),
('GCSE English', 'Summer Term', 36, 'Non-fiction Practice & Unseen Poetry', 'Comparing nonfiction and viewpoints practice. Unseen poetry: timed exam practice'),
('GCSE English', 'Summer Term', 37, 'Mixed Practice & Thematic Essays', 'Paper 1 & 2 mixed timed questions practice. Poetry anthology: thematic essay writing'),
('GCSE English', 'Summer Term', 38, 'Exam Technique & Essay Finalization', 'Exam technique workshops (timing, planning). Set texts: essay writing finalization'),
('GCSE English', 'Summer Term', 39, 'Skills Consolidation & Advanced Analysis', 'Grammar & vocabulary skills consolidation. Unseen poetry: advanced language & structure analysis'),
('GCSE English', 'Summer Term', 40, 'Question Review & Final Practice', 'Revision of question types (Q1-Q5). Poetry anthology: final essay practice'),
('GCSE English', 'Summer Term', 41, 'Paper 1 Mock & Exam Essays', 'Paper 1 full mock exam. Set texts: exam essay writing'),
('GCSE English', 'Summer Term', 42, 'Paper 2 Mock & Comparative Essays', 'Paper 2 full mock exam. Comparative poetry essay timed practice'),
('GCSE English', 'Summer Term', 43, 'Feedback & Critical Review', 'Feedback and target-focused revision. Set texts: critical theme and character review'),
('GCSE English', 'Summer Term', 44, 'Final Skills & Comparative Review', 'Final revision: exam skills & strategies. Poetry anthology: final comparative review'),
('GCSE English', 'Summer Term', 45, 'Final Writing & Context Review', 'Final timed writing practice. Set texts: review of context and impact'),
('GCSE English', 'Summer Term', 46, 'Final Reading & Unseen Poetry', 'Final reading skills practice. Unseen poetry: exam preparation'),
('GCSE English', 'Summer Term', 47, 'Exam Technique & Literature Review', 'Exam technique & stress management. Literature: final review sessions'),
('GCSE English', 'Summer Term', 48, 'Final Readiness & Feedback', 'Final exam readiness & overall review. Final exam practice & personalized feedback'),

-- Final 4 Weeks: Weeks 49-52
('GCSE English', 'Final 4 Weeks', 49, 'Personalized Review', 'Personalized review: weak areas in Paper 1 & Paper 2'),
('GCSE English', 'Final 4 Weeks', 50, 'Mock Exam Week', 'Mock exam week: Paper 1 & Paper 2 full papers'),
('GCSE English', 'Final 4 Weeks', 51, 'Detailed Feedback', 'Detailed feedback & exam strategy adjustment'),
('GCSE English', 'Final 4 Weeks', 52, 'Final Confidence Building', 'Final confidence building: timed practice & Q&A sessions'),

-- Insert GCSE Biology lesson plans
('GCSE Biology', 'Year Plan', 1, 'Cell Biology', 'Cell structure and function'),
('GCSE Biology', 'Year Plan', 2, 'Cell Biology', 'Cell division (mitosis and meiosis). Transport across cell membranes (diffusion, osmosis, active transport)'),
('GCSE Biology', 'Year Plan', 3, 'Organisation', 'Organisation of tissues and organs in animals and plants'),
('GCSE Biology', 'Year Plan', 4, 'Organisation', 'The human digestive system and enzymes. The circulatory system and blood'),
('GCSE Biology', 'Year Plan', 5, 'Infection and Response', 'Pathogens and diseases'),
('GCSE Biology', 'Year Plan', 6, 'Infection and Response', 'The immune system and vaccination. Antibiotics and resistance'),
('GCSE Biology', 'Year Plan', 7, 'Bioenergetics', 'Photosynthesis and factors affecting it'),
('GCSE Biology', 'Year Plan', 8, 'Bioenergetics', 'Respiration (aerobic and anaerobic). Energy transfer in ecosystems'),
('GCSE Biology', 'Year Plan', 9, 'Homeostasis and Response', 'Homeostasis in humans (temperature regulation, blood sugar levels)'),
('GCSE Biology', 'Year Plan', 10, 'Homeostasis and Response', 'The nervous system and endocrine system. The role of hormones and feedback mechanisms'),
('GCSE Biology', 'Year Plan', 11, 'Genetics and Evolution', 'DNA structure and function'),
('GCSE Biology', 'Year Plan', 12, 'Genetics and Evolution', 'Genetic inheritance (Mendelian genetics). Evolution and natural selection'),
('GCSE Biology', 'Year Plan', 13, 'Variation and Evolution', 'Genetic and environmental causes of variation'),
('GCSE Biology', 'Year Plan', 14, 'Variation and Evolution', 'Evolutionary theory and supporting evidence. Human evolution and genetics'),
('GCSE Biology', 'Year Plan', 15, 'Ecology: Ecosystems and Biodiversity', 'Components of ecosystems (producers, consumers, decomposers)'),
('GCSE Biology', 'Year Plan', 16, 'Ecology: Ecosystems and Biodiversity', 'Biodiversity and conservation. Human impacts on the environment'),
('GCSE Biology', 'Year Plan', 17, 'Plant Biology: Structure and Function', 'Structure of roots, stems, leaves, and flowers'),
('GCSE Biology', 'Year Plan', 18, 'Plant Biology: Structure and Function', 'Plant reproduction (sexual and asexual). Growth and development stages in plants'),
('GCSE Biology', 'Year Plan', 19, 'Human Anatomy and Physiology', 'The skeletal system (bones, joints, muscles)'),
('GCSE Biology', 'Year Plan', 20, 'Human Anatomy and Physiology', 'The respiratory system and gas exchange. The excretory system and osmoregulation'),
('GCSE Biology', 'Year Plan', 21, 'Health and Disease: Non-communicable Diseases', 'Non-communicable diseases (e.g. cancer, cardiovascular disease)'),
('GCSE Biology', 'Year Plan', 22, 'Health and Disease: Non-communicable Diseases', 'Lifestyle impacts (diet, exercise). Genetic predispositions to disease'),
('GCSE Biology', 'Year Plan', 23, 'Scientific Methodology and Practical Investigations', 'Designing biological experiments and testing variables'),
('GCSE Biology', 'Year Plan', 24, 'Scientific Methodology and Practical Investigations', 'Data analysis and evaluation. Scientific methods, safety, and measurements'),
('GCSE Biology', 'Year Plan', 25, 'Interactions and Interdependencies', 'Interactions within ecosystems'),
('GCSE Biology', 'Year Plan', 26, 'Interactions and Interdependencies', 'Predator-prey relationships and competition. Adaptations to environmental changes'),
('GCSE Biology', 'Year Plan', 27, 'Energy in Ecosystems', 'Energy flow in food chains and food webs'),
('GCSE Biology', 'Year Plan', 28, 'Energy in Ecosystems', 'Nutrient cycles (carbon and nitrogen). Ecological pyramids and energy efficiency'),
('GCSE Biology', 'Year Plan', 29, 'Advanced Genetics', 'Genetic modification and biotechnology'),
('GCSE Biology', 'Year Plan', 30, 'Advanced Genetics', 'Ethical considerations in genetics. Gene therapy and its uses'),
('GCSE Biology', 'Year Plan', 31, 'Review of Cell Biology & Organisation', 'Recap of cellular structures and membrane transport'),
('GCSE Biology', 'Year Plan', 32, 'Review of Cell Biology & Organisation', 'Tissue and organ systems. Practice questions and applied understanding'),
('GCSE Biology', 'Year Plan', 33, 'Review of Infection, Immunity & Bioenergetics', 'Review immune responses and diseases'),
('GCSE Biology', 'Year Plan', 34, 'Review of Infection, Immunity & Bioenergetics', 'Photosynthesis and respiration. Practice questions and revision tasks'),
('GCSE Biology', 'Year Plan', 35, 'Review of Ecology & Environment', 'Ecosystems, biodiversity, conservation'),
('GCSE Biology', 'Year Plan', 36, 'Review of Ecology & Environment', 'Human environmental impacts. Interactions and adaptations in ecosystems'),
('GCSE Biology', 'Year Plan', 37, 'Review of Genetics & Evolution', 'DNA, inheritance patterns, and genetic variation'),
('GCSE Biology', 'Year Plan', 38, 'Review of Genetics & Evolution', 'Evolutionary processes and natural selection. Extended genetics (biotech, ethics)'),
('GCSE Biology', 'Year Plan', 39, 'Review of Human Systems', 'Circulatory, respiratory, nervous, and endocrine systems'),
('GCSE Biology', 'Year Plan', 40, 'Review of Human Systems', 'Homeostasis and body regulation. Lifestyle diseases and prevention'),
('GCSE Biology', 'Year Plan', 41, 'Applied Science: Case Studies', 'Applications of biotechnology in medicine and farming'),
('GCSE Biology', 'Year Plan', 42, 'Applied Science: Case Studies', 'Human impact on biodiversity. Environmental case studies (e.g. conservation, global warming)'),
('GCSE Biology', 'Year Plan', 43, 'Practical Applications & Lab Skills', 'Planning and executing experiments'),
('GCSE Biology', 'Year Plan', 44, 'Practical Applications & Lab Skills', 'Measuring, recording, and evaluating data. Lab-based problem solving'),
('GCSE Biology', 'Year Plan', 45, 'Scientific Communication & Data Interpretation', 'Reading graphs, tables, and diagrams'),
('GCSE Biology', 'Year Plan', 46, 'Scientific Communication & Data Interpretation', 'Writing scientific reports. Interpreting data and drawing conclusions'),
('GCSE Biology', 'Year Plan', 47, 'Problem Solving and Exam Techniques', 'Tackling extended response questions'),
('GCSE Biology', 'Year Plan', 48, 'Problem Solving and Exam Techniques', 'Common pitfalls and how to avoid them. Understanding mark schemes and assessment objectives'),
('GCSE Biology', 'Year Plan', 49, 'Full Practice Papers & Analysis', 'Timed exam-style papers'),
('GCSE Biology', 'Year Plan', 50, 'Full Practice Papers & Analysis', 'Marking and reviewing answers. Identifying weak areas and closing knowledge gaps'),
('GCSE Biology', 'Year Plan', 51, 'Final Consolidation and Mock Exam', 'Mixed-topic final assessments'),
('GCSE Biology', 'Year Plan', 52, 'Final Consolidation and Mock Exam', 'Mock paper under exam conditions. Final feedback, confidence building, and next steps');
